apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sysbenches.sysbench.example.com
spec:
  group: sysbench.example.com
  names:
    kind: Sysbench
    listKind: SysbenchList
    plural: sysbenches
    singular: sysbench
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
